sudo: required
service:
  - docker

before_install:
  - docker build -t vietletrung/vietletrung -f Dockerfile.dev .

script:
  - docker run -e CI=true vietletrung/vietletrung npm run test -- --coverage